# Generated by Django 3.1.3 on 2020-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201128_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='savedump',
            field=models.TextField(default=''),
        ),
    ]
