# Generated by Django 3.1.3 on 2021-02-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210215_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_yearly',
            field=models.BooleanField(default=False),
        ),
    ]
