# Generated by Django 3.1.3 on 2021-05-12 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modeldata_modelmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCoefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intercept', models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Intercept')),
                ('median_base_price_log', models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Median Base Price Log')),
                ('tpr_discount', models.DecimalField(decimal_places=15, max_digits=20, verbose_name='TPR Discount')),
                ('tpr_discount_lag1', models.DecimalField(decimal_places=15, max_digits=20)),
                ('tpr_discount_lag2', models.DecimalField(decimal_places=15, max_digits=20)),
                ('catalogue', models.DecimalField(decimal_places=15, max_digits=20)),
                ('display', models.DecimalField(decimal_places=15, max_digits=20)),
                ('acv', models.DecimalField(decimal_places=15, max_digits=20)),
                ('si', models.DecimalField(decimal_places=15, max_digits=20)),
                ('si_month', models.DecimalField(decimal_places=15, max_digits=20)),
                ('si_quarter', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_1_crossretailer_discount', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_1_crossretailer_log_price', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_1_intra_discount', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_2_intra_discount', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_3_intra_discount', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_4_intra_discount', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_5_intra_discount', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_1_intra_log_price', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_2_intra_log_price', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_3_intra_log_price', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_4_intra_log_price', models.DecimalField(decimal_places=15, max_digits=20)),
                ('c_5_intra_log_price', models.DecimalField(decimal_places=15, max_digits=20)),
                ('category_trend', models.DecimalField(decimal_places=15, max_digits=20)),
                ('trend_month', models.DecimalField(decimal_places=15, max_digits=20)),
                ('trend_quarter', models.DecimalField(decimal_places=15, max_digits=20)),
                ('trend_year', models.DecimalField(decimal_places=15, max_digits=20)),
                ('month_no', models.DecimalField(decimal_places=15, max_digits=20)),
                ('flag_promotype_motivation', models.DecimalField(decimal_places=15, max_digits=20)),
                ('flag_promotype_n_pls_1', models.DecimalField(decimal_places=15, max_digits=20)),
                ('flag_promotype_traffic', models.DecimalField(decimal_places=15, max_digits=20)),
                ('flag_nonpromo_1', models.DecimalField(decimal_places=15, max_digits=20)),
                ('flag_nonpromo_2', models.DecimalField(decimal_places=15, max_digits=20)),
                ('flag_nonpromo_3', models.DecimalField(decimal_places=15, max_digits=20)),
                ('flag_promo_1', models.DecimalField(decimal_places=15, max_digits=20)),
                ('flag_promo_2', models.DecimalField(decimal_places=15, max_digits=20)),
                ('flag_promo_3', models.DecimalField(decimal_places=15, max_digits=20)),
                ('holiday_flag_1', models.DecimalField(decimal_places=15, max_digits=20)),
                ('holiday_flag_2', models.DecimalField(decimal_places=15, max_digits=20)),
                ('holiday_flag_3', models.DecimalField(decimal_places=15, max_digits=20)),
                ('holiday_flag_4', models.DecimalField(decimal_places=15, max_digits=20)),
                ('holiday_flag_5', models.DecimalField(decimal_places=15, max_digits=20)),
                ('holiday_flag_6', models.DecimalField(decimal_places=15, max_digits=20)),
                ('holiday_flag_7', models.DecimalField(decimal_places=15, max_digits=20)),
                ('holiday_flag_8', models.DecimalField(decimal_places=15, max_digits=20)),
                ('holiday_flag_9', models.DecimalField(decimal_places=15, max_digits=20)),
                ('holiday_flag_10', models.DecimalField(decimal_places=15, max_digits=20)),
                ('wmape', models.DecimalField(decimal_places=15, max_digits=20)),
                ('rsq', models.DecimalField(decimal_places=15, max_digits=20)),
                ('model_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficient', to='core.modelmeta')),
            ],
            options={
                'db_table': 'model_coefficient',
            },
        ),
    ]
