# Generated by Django 3.1.3 on 2021-05-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_modelcoefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmeta',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
