# Generated by Django 3.1.3 on 2021-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_modelmeta_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldata',
            name='gmac_percent_lsv',
            field=models.DecimalField(decimal_places=15, default=0.7292, max_digits=20),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='list_price',
            field=models.DecimalField(decimal_places=15, default=168.43, max_digits=20),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='off_inv',
            field=models.DecimalField(decimal_places=15, default=0.1993, max_digits=20),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='on_inv',
            field=models.DecimalField(decimal_places=15, default=0.05, max_digits=20),
        ),
    ]
