# Generated by Django 3.1.3 on 2021-05-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210520_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmeta',
            name='brand_filter',
            field=models.CharField(default='', max_length=100, verbose_name='Brand Filter'),
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='brand_format_filter',
            field=models.CharField(default='', max_length=100, verbose_name='Brand Format Filter'),
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='strategic_cell_filter',
            field=models.CharField(default='', max_length=100, verbose_name='Strategic Cell Filter'),
        ),
        migrations.CreateModel(
            name='ModelROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_inv', models.DecimalField(decimal_places=15, default=0.05, max_digits=20)),
                ('off_inv', models.DecimalField(decimal_places=15, default=0.1993, max_digits=20)),
                ('list_price', models.DecimalField(decimal_places=15, default=168.43, max_digits=20)),
                ('gmac_percent_lsv', models.DecimalField(decimal_places=15, default=0.7292, max_digits=20)),
                ('model_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi', to='core.modelmeta')),
            ],
        ),
    ]
