# Generated by Django 3.1.3 on 2021-05-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210525_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelroi',
            old_name='gmac_percent_lsv',
            new_name='gmac',
        ),
        migrations.RemoveField(
            model_name='modeldata',
            name='gmac_percent_lsv',
        ),
        migrations.RemoveField(
            model_name='modeldata',
            name='list_price',
        ),
        migrations.RemoveField(
            model_name='modeldata',
            name='off_inv',
        ),
        migrations.RemoveField(
            model_name='modeldata',
            name='on_inv',
        ),
        migrations.AddField(
            model_name='modelroi',
            name='average_weight_in_grams',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='modelroi',
            name='week',
            field=models.IntegerField(null=True, verbose_name='Week'),
        ),
        migrations.AddField(
            model_name='modelroi',
            name='weighted_weight_in_grams',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='modelroi',
            name='wk_sold_avg_price_byppg',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20, verbose_name='Week Sold Average Price by PPG'),
        ),
        migrations.AddField(
            model_name='modelroi',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Year'),
        ),
        migrations.AddConstraint(
            model_name='modelmeta',
            constraint=models.UniqueConstraint(fields=('account_name', 'corporate_segment', 'product_group'), name='retailers'),
        ),
        migrations.AlterModelTable(
            name='modelroi',
            table='model_roi',
        ),
    ]
