# Generated by Django 3.1.3 on 2021-05-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210526_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldata',
            name='period',
            field=models.CharField(max_length=10, verbose_name='Period'),
        ),
    ]
