# Generated by Django 3.1.3 on 2021-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210526_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelroi',
            name='average_weight_in_grams',
        ),
        migrations.RemoveField(
            model_name='modelroi',
            name='weighted_weight_in_grams',
        ),
        migrations.RemoveField(
            model_name='modelroi',
            name='wk_sold_avg_price_byppg',
        ),
        migrations.AddField(
            model_name='modelcoefficient',
            name='average_weight_in_grams',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='modelcoefficient',
            name='weighted_weight_in_grams',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='wk_sold_avg_price_byppg',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20, verbose_name='Week Sold Average Price by PPG'),
        ),
    ]
