# Generated by Django 3.1.3 on 2021-05-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210531_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmeta',
            name='brand_filter',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Brand Filter'),
        ),
        migrations.AlterField(
            model_name='modelmeta',
            name='brand_format_filter',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Brand Format Filter'),
        ),
        migrations.AlterField(
            model_name='modelmeta',
            name='strategic_cell_filter',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Strategic Cell Filter'),
        ),
    ]
