# Generated by Django 3.1.3 on 2021-06-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210531_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldata',
            name='base_unit',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='incremental_unit',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20, null=True),
        ),
    ]
