# Generated by Django 3.1.3 on 2021-06-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210601_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldata',
            name='base_unit',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='incremental_unit',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True),
        ),
    ]
