# Generated by Django 3.1.3 on 2021-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_coeffmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelroi',
            name='activity_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelroi',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='modelroi',
            name='mechanic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelroi',
            name='month',
            field=models.IntegerField(null=True, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='modelroi',
            name='neilson_sku_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coeffmap',
            name='coefficient_new',
            field=models.CharField(max_length=100, verbose_name='Coefficient New'),
        ),
        migrations.AlterField(
            model_name='coeffmap',
            name='coefficient_old',
            field=models.CharField(max_length=100, verbose_name='Cefficient'),
        ),
    ]
