# Generated by Django 3.1.3 on 2021-06-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210608_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelroi',
            name='discount_nrv',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
    ]
