# Generated by Django 3.1.3 on 2021-06-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_modelroi_discount_nrv'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='scenario_type',
            field=models.CharField(choices=[('pricing', 'pricing'), ('promo', 'promo')], default='pricing', max_length=20),
        ),
    ]
