# Generated by Django 3.1.3 on 2021-06-11 07:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_scenario_scenario_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcoefficient',
            name='co_investment',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Co investment'),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='co_investment',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Co investment'),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='tpr_discount',
            field=models.DecimalField(decimal_places=15, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='TPR Discount'),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='tpr_discount_lag1',
            field=models.DecimalField(decimal_places=15, max_digits=20, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='tpr_discount_lag2',
            field=models.DecimalField(decimal_places=15, max_digits=20, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='tpr_discount',
            field=models.DecimalField(decimal_places=15, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='TPR Discount'),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='tpr_discount_lag1',
            field=models.DecimalField(decimal_places=15, max_digits=20, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='tpr_discount_lag2',
            field=models.DecimalField(decimal_places=15, max_digits=20, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='modelroi',
            name='gmac',
            field=models.DecimalField(decimal_places=15, default=0.7292, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='modelroi',
            name='month',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='modelroi',
            name='off_inv',
            field=models.DecimalField(decimal_places=15, default=0.1993, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='modelroi',
            name='on_inv',
            field=models.DecimalField(decimal_places=15, default=0.05, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='modelroi',
            name='week',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Week'),
        ),
    ]
