# Generated by Django 3.1.3 on 2021-06-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210611_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmeta',
            name='slug',
            field=models.SlugField(default='', max_length=255, null=True, unique=True),
        ),
    ]
