# Generated by Django 3.1.3 on 2021-06-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210614_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmeta',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
