# Generated by Django 3.1.3 on 2021-06-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210614_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldata',
            name='wk_sold_avg_price_byppg',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20, null=True, verbose_name='Week Sold Average Price by PPG'),
        ),
    ]
