# Generated by Django 3.1.3 on 2021-06-15 04:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210615_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcoefficient',
            name='co_investment',
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='co_investment',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Co investment'),
        ),
    ]
