# Generated by Django 3.1.3 on 2021-06-15 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_modeldata_promo_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldata',
            name='month',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='week',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Week'),
        ),
    ]
