# Generated by Django 3.1.3 on 2021-06-15 12:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210615_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coeffmap',
            name='value',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='acv',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_1_crossretailer_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_1_crossretailer_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_1_intra_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_1_intra_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_2_intra_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_2_intra_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_3_intra_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_3_intra_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_4_intra_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_4_intra_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_5_intra_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='c_5_intra_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='catalogue',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='category_trend',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='display',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='flag_nonpromo_1',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='flag_nonpromo_2',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='flag_nonpromo_3',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='flag_promo_1',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='flag_promo_2',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='flag_promo_3',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='flag_promotype_motivation',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='flag_promotype_n_pls_1',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='flag_promotype_traffic',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='holiday_flag_1',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='holiday_flag_10',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='holiday_flag_2',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='holiday_flag_3',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='holiday_flag_4',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='holiday_flag_5',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='holiday_flag_6',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='holiday_flag_7',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='holiday_flag_8',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='holiday_flag_9',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='intercept',
            field=models.DecimalField(decimal_places=15, max_digits=30, verbose_name='Intercept'),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='median_base_price_log',
            field=models.DecimalField(decimal_places=15, max_digits=30, verbose_name='Median Base Price Log'),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='month_no',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='rsq',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='si',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='si_month',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='si_quarter',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='tpr_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='TPR Discount'),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='tpr_discount_lag1',
            field=models.DecimalField(decimal_places=15, max_digits=30, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='tpr_discount_lag2',
            field=models.DecimalField(decimal_places=15, max_digits=30, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='trend_month',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='trend_quarter',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='trend_year',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelcoefficient',
            name='wmape',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='acv',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='average_weight_in_grams',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_1_crossretailer_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_1_crossretailer_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_1_intra_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_1_intra_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_2_intra_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_2_intra_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_3_intra_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_3_intra_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_4_intra_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_4_intra_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_5_intra_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='c_5_intra_log_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='catalogue',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='category_trend',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='co_investment',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Co investment'),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='display',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='flag_nonpromo_1',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='flag_nonpromo_2',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='flag_nonpromo_3',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='flag_promo_1',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='flag_promo_2',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='flag_promo_3',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='flag_promotype_motivation',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='flag_promotype_n_pls_1',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='flag_promotype_traffic',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='holiday_flag_1',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='holiday_flag_10',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='holiday_flag_2',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='holiday_flag_3',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='holiday_flag_4',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='holiday_flag_5',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='holiday_flag_6',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='holiday_flag_7',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='holiday_flag_8',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='holiday_flag_9',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='intercept',
            field=models.DecimalField(decimal_places=15, max_digits=30, verbose_name='Intercept'),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='median_base_price_log',
            field=models.DecimalField(decimal_places=15, max_digits=30, verbose_name='Median Base Price Log'),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='month_no',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='promo_depth',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Promo Depth'),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='si',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='si_month',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='si_quarter',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='tpr_discount',
            field=models.DecimalField(decimal_places=15, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='TPR Discount'),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='tpr_discount_lag1',
            field=models.DecimalField(decimal_places=15, max_digits=30, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='tpr_discount_lag2',
            field=models.DecimalField(decimal_places=15, max_digits=30, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='trend_month',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='trend_quarter',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='trend_year',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='weighted_weight_in_grams',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='wk_sold_avg_price_byppg',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True, verbose_name='Week Sold Average Price by PPG'),
        ),
        migrations.AlterField(
            model_name='modelroi',
            name='discount_nrv',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='modelroi',
            name='gmac',
            field=models.DecimalField(decimal_places=15, default=0.7292, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='modelroi',
            name='list_price',
            field=models.DecimalField(decimal_places=15, default=168.43, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='modelroi',
            name='off_inv',
            field=models.DecimalField(decimal_places=15, default=0.1993, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='modelroi',
            name='on_inv',
            field=models.DecimalField(decimal_places=15, default=0.05, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
    ]
