# Generated by Django 3.1.3 on 2021-06-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210615_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldata',
            name='optimiser_flag',
            field=models.BooleanField(default=False),
        ),
    ]
