# Generated by Django 3.1.3 on 2021-06-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_modeldata_optimiser_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioplannermetrics',
            name='week',
            field=models.IntegerField(default=1, null=True, verbose_name='week'),
        ),
    ]
