# Generated by Django 3.1.3 on 2021-06-22 13:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_scenarioplannermetrics_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('corporate_segment', models.CharField(max_length=100, verbose_name='Corporate Segment')),
                ('product_group', models.CharField(max_length=100, verbose_name='Product Group')),
            ],
            options={
                'db_table': 'pricing_save',
            },
        ),
        migrations.CreateModel(
            name='PromoSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('corporate_segment', models.CharField(max_length=100, verbose_name='Corporate Segment')),
                ('product_group', models.CharField(max_length=100, verbose_name='Product Group')),
                ('promo_elasticity', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('saved_pricing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_promo_saved', to='core.pricingsave')),
            ],
            options={
                'db_table': 'promo_save',
            },
        ),
        migrations.CreateModel(
            name='SavedScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_type', models.CharField(choices=[('pricing', 'pricing'), ('promo', 'promo')], default='pricing', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('comments', models.CharField(default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromoWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('week', models.IntegerField(default=1, null=True, verbose_name='week')),
                ('promo_depth', models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Promo Depth')),
                ('co_investment', models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Co investment')),
                ('promo_mechanic', models.CharField(max_length=100, verbose_name='Promo Mechanic')),
                ('pricing_save', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_week', to='core.promosave')),
            ],
            options={
                'db_table': 'promo_week_save',
            },
        ),
        migrations.AddField(
            model_name='promosave',
            name='saved_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_saved', to='core.savedscenario'),
        ),
        migrations.CreateModel(
            name='PricingWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('week', models.IntegerField(default=1, null=True, verbose_name='week')),
                ('lp_increase', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Increased LP')),
                ('rsp_increase', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Increased RSP')),
                ('cogs_increase', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Increased COGS')),
                ('pricing_save', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_week', to='core.pricingsave')),
            ],
            options={
                'db_table': 'pricing_week_save',
            },
        ),
        migrations.AddField(
            model_name='pricingsave',
            name='saved_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_saved', to='core.savedscenario'),
        ),
    ]
