# Generated by Django 3.1.3 on 2021-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210622_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoweek',
            options={'ordering': ('week',)},
        ),
        migrations.AlterField(
            model_name='promoweek',
            name='promo_mechanic',
            field=models.CharField(max_length=100, null=True, verbose_name='Promo Mechanic'),
        ),
    ]
