# Generated by Django 3.1.3 on 2021-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210624_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingweek',
            name='base_price_elasticity',
            field=models.DecimalField(decimal_places=3, default=-2.03, max_digits=8, verbose_name='Modified base price elasticity'),
        ),
    ]
