# Generated by Django 3.1.3 on 2021-06-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_optimizersave'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizersave',
            name='saved_scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimizer_saved', to='core.savedscenario'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_type',
            field=models.CharField(choices=[('pricing', 'pricing'), ('promo', 'promo'), ('optimizer', 'optimizer')], default='pricing', max_length=20),
        ),
    ]
