# Generated by Django 3.1.3 on 2021-06-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210628_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizersave',
            name='base_base',
        ),
        migrations.RemoveField(
            model_name='optimizersave',
            name='base_incremental',
        ),
        migrations.RemoveField(
            model_name='optimizersave',
            name='base_promo',
        ),
        migrations.RemoveField(
            model_name='optimizersave',
            name='base_units',
        ),
        migrations.RemoveField(
            model_name='optimizersave',
            name='date',
        ),
        migrations.RemoveField(
            model_name='optimizersave',
            name='optimum_base',
        ),
        migrations.RemoveField(
            model_name='optimizersave',
            name='optimum_incremental',
        ),
        migrations.RemoveField(
            model_name='optimizersave',
            name='optimum_units',
        ),
        migrations.AddField(
            model_name='optimizersave',
            name='optimum_co_investment',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='optimizersave',
            name='week',
            field=models.IntegerField(default=1, null=True, verbose_name='week'),
        ),
        migrations.AlterField(
            model_name='savedscenario',
            name='scenario_type',
            field=models.CharField(choices=[('pricing', 'pricing'), ('promo', 'promo'), ('optimizer', 'optimizer')], default='pricing', max_length=20),
        ),
    ]
