# Generated by Django 3.1.3 on 2021-07-01 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210628_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizersave',
            name='promo_save',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimizer_promo', to='core.promosave'),
        ),
    ]
