# Generated by Django 3.1.3 on 2021-07-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_optimizersave_promo_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizersave',
            name='pricing_save',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimzer_pricing', to='core.pricingsave'),
        ),
    ]
