# Generated by Django 3.1.3 on 2021-07-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20210707_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_retailers',
            field=models.ManyToManyField(related_name='allowed_retailers', to='core.ModelMeta'),
        ),
    ]
