# Generated by Django 3.1.3 on 2021-07-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_user_allowed_retailers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allowed_retailers',
            field=models.ManyToManyField(blank=True, related_name='allowed_retailers', to='core.ModelMeta'),
        ),
    ]
