# Generated by Django 3.1.3 on 2021-07-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20210708_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingsave',
            name='corporate_segment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Corporate Segment'),
        ),
        migrations.AlterField(
            model_name='promosave',
            name='corporate_segment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Corporate Segment'),
        ),
    ]
