# Generated by Django 3.1.3 on 2021-08-14 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_optimizersave_mechanic'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('quater', models.IntegerField(verbose_name='Quater')),
                ('month', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month')),
                ('week', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Week')),
                ('date', models.DateField(verbose_name='Date')),
                ('holiday_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('retailer', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'db_table': 'holiday_calendar',
            },
        ),
    ]
