# Generated by Django 3.1.3 on 2021-08-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_holidaycalendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidaycalendar',
            old_name='holiday_name',
            new_name='magnit_flag',
        ),
        migrations.RenameField(
            model_name='holidaycalendar',
            old_name='retailer',
            new_name='x5_flag',
        ),
        migrations.AddField(
            model_name='holidaycalendar',
            name='x5_magnit_flag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
