# Generated by Django 3.1.3 on 2021-08-16 13:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20210815_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldata',
            name='death_rate',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Co investment'),
        ),
    ]
