# Generated by Django 3.1.3 on 2021-10-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20210816_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsave',
            name='cogs_date',
            field=models.DateField(blank=True, null=True, verbose_name='Cogs Date'),
        ),
        migrations.AddField(
            model_name='pricingsave',
            name='list_price_date',
            field=models.DateField(blank=True, null=True, verbose_name='List Price Date'),
        ),
        migrations.AddField(
            model_name='pricingsave',
            name='rsp_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rsp Date'),
        ),
    ]
