# Generated by Django 3.1.3 on 2021-10-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20211004_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsave',
            name='promo_save',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_promo_map', to='core.promosave'),
        ),
    ]
