# Generated by Django 3.1.3 on 2021-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20211029_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsave',
            name='follow_competition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingsave',
            name='inc_elasticity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Increased base price elasticity'),
        ),
        migrations.AddField(
            model_name='pricingsave',
            name='inc_net_elasticity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Increased net price elasticity'),
        ),
    ]
