# Generated by Django 3.1.3 on 2021-10-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20211029_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingweek',
            name='base_promo_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='base cogs'),
        ),
        migrations.AddField(
            model_name='pricingweek',
            name='promo_increase',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='base cogs'),
        ),
    ]
