# Generated by Django 3.1.3 on 2021-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20211029_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsave',
            name='promo_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rsp Date'),
        ),
    ]
