# Generated by Django 3.1.3 on 2021-11-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_pricingsave_promo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsave',
            name='base_elasticity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='base price elasticity'),
        ),
        migrations.AddField(
            model_name='pricingsave',
            name='base_net_elasticity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='base net price elasticity'),
        ),
        migrations.AlterField(
            model_name='pricingweek',
            name='base_promo_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='base promo price'),
        ),
        migrations.AlterField(
            model_name='pricingweek',
            name='promo_increase',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Increased promo'),
        ),
    ]
