# Generated by Django 3.1.3 on 2021-11-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20211112_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsave',
            name='cogs_increase',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Increased COGS'),
        ),
        migrations.AddField(
            model_name='pricingsave',
            name='lp_increase',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Increased LP'),
        ),
        migrations.AddField(
            model_name='pricingsave',
            name='rsp_increase',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Increased RSP'),
        ),
    ]
