# Generated by Django 3.1.3 on 2021-11-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20211112_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsave',
            name='promo_increase',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Increased promo'),
        ),
    ]
