# Generated by Django 3.1.3 on 2021-11-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_pricingsave_promo_increase'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsave',
            name='is_tpr_constant',
            field=models.BooleanField(default=False),
        ),
    ]
