# Generated by Django 3.1.3 on 2021-06-11 06:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimiser', '0002_auto_20210611_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdb',
            name='percent',
            field=models.DecimalField(decimal_places=15, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='percent'),
        ),
    ]
